### PR TITLE
Added Jest unit test framework dependency and configuration

### PR DESCRIPTION
**Pull request by rafapaezbas**
Added Jest unit test framework dependency. It looks interesting, specially the watch mode where you can execute only failed tests, or some subset of them.

### CODE REVIEW

**Comment by javieraviles** [comment]
were you able to mock typeorm repositories in the controller?

**Comment by rafapaezbas** [comment]
let me have a look and I will let you know. Im going to try to add an example with the mock. Thnx for the review ;)

**Comment by javieraviles** [comment]
Something like `jest.mock('typeorm', () => ({ getRepository: jest.fn() }));` should do. https://stackoverflow.com/questions/61693597/how-to-mock-typeorms-getcustomrepository

**Comment by javieraviles** [comment]
just fixed a couple of things in master by the way

**Comment by rafapaezbas** [comment]
Still working on it, adding some fine tests for UserController as example for any other controller.

**Comment by rafapaezbas** [comment]
Added 100% coverage to UserController class.

I am not very familiar with Jest and Typescript types system. I do not know if Jest is the best possible option... maybe you should think about it.

**Comment by javieraviles** [comment]
It looks just great, if you want pull master into your branch and we can merge this into master and release 1.8 :)

**Comment by rafapaezbas** [comment]
Pulled master into the branch, have a look

**Comment by javieraviles** [comment]
good to go :)

**Pull request merged**
