### PR TITLE
Add prettier for consistant formatting of the files

### PR DESCRIPTION
**Pull request by SimonScholz**
Hi,
I really like this project and modern stack.
With prettier you´d gain consistant formatting of your files and therefore can enforce readability and comparing files for pull requests and such will be easier ;-)

### CODE REVIEW

**Comment by javieraviles** [comment]
Hi! Sorry for the delay, but my priority was first fix the CI as actions was breaking backwards compatibility on some of the actions repos and it was not working here anymore. Now is fine so this looks like a good next improvement. 

One suggestion I would say is, as the project uses tslint at the moment, should we not tell tslint to forget about format and do the rest as prettier is now here?

had a quick read at this and sounds good
https://alexjover.com/blog/use-prettier-with-tslint-and-be-happy/

we would extend tslint config with something like

`{
  "extends": [
    "tslint:latest",
    "tslint-config-prettier"
  ]
}`


what do you think? thanks again and sorry for the delay! :)

**Comment by SimonScholz** [comment]
Totally agree @javieraviles I´ll add this and also resolve the merge conflicts.

**Comment by javieraviles** [comment]
sounds like a plan; if anything, im around

**Comment by javieraviles** [comment]
Just started the migration from TSLint to ESLint so the prettier interaction would be more in this direction

` module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    plugins: [
      '@typescript-eslint',
    ],
    extends: [
      'eslint:recommended',
      'plugin:@typescript-eslint/eslint-recommended',
      'plugin:@typescript-eslint/recommended',
+     'prettier/@typescript-eslint',
    ],
  };`

as soon as im finished with the migration, will take this over if dont see much action here :)

**Comment by javieraviles** [comment]
Im pretty happy about the style checking of ESLint too, so I think I'm not addint prettier at the moment; doesn't add too much value and would make this a bit more complex for people who are just learning. Thanks anyway for raising the topic, I learnt a lot!

BR

**Pull request closed without merging**
